/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.{js,ts,tsx}', './components/**/*.{js,ts,tsx}'],

  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#393939",
        "primary-container": "#d4d4d4",
        "on-surface-variant": "#c6c6c6",
        "on-tertiary-fixed": "#ffffff",
        "on-primary-fixed-variant": "#e2e2e2",
        "on-secondary-fixed-variant": "#7e0004",
        "primary": "#ffffff",
        "on-surface": "#e2e2e2",
        "surface-variant": "#353535",
        "surface-container-highest": "#353535",
        "on-tertiary-fixed-variant": "#72fe88",
        "inverse-surface": "#e2e2e2",
        "on-secondary": "#410001",
        "outline": "#919191",
        "surface-container-lowest": "#0e0e0e",
        "on-error": "#690005",
        "tertiary-container": "#00a741",
        "secondary-fixed": "#ffb4aa",
        "primary-fixed": "#5d5f5f",
        "error-container": "#93000a",
        "tertiary": "#72fe88",
        "secondary-container": "#930005",
        "surface-dim": "#131313",
        "surface-container-high": "#2a2a2a",
        "surface-container": "#1f1f1f",
        "secondary-fixed-dim": "#ff8a7b",
        "on-primary": "#1a1c1c",
        "outline-variant": "#474747",
        "tertiary-fixed": "#006e28",
        "background": "#000000",
        "on-background": "#e2e2e2",
        "surface": "#131313",
        "surface-tint": "#c6c6c7",
        "secondary": "#ffb4aa",
        "on-primary-container": "#000000",
        "surface-container-low": "#1b1b1b",
        "error": "#ffb4ab",
        "on-tertiary": "#002107",
        "inverse-on-surface": "#303030"
      },
      fontFamily: {
        "headline": ["Inter_900Black", "Inter_800ExtraBold", "Inter_700Bold"],
        "body": ["Inter_400Regular"],
        "label": ["SpaceGrotesk_400Regular", "SpaceGrotesk_300Light", "SpaceGrotesk_500Medium", "SpaceGrotesk_700Bold"]
      },
    },
  },
  plugins: [],
};
